project:
  type: website
  # output-dir: docs # for flexibility in building GitHub pages

website:
  title: "Title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: sandstone
      dark: vapor
    css: styles.css
    toc: true
    fig-align: center
    reference-location: margin

editor: visual

