project:
  type: website
  output-dir: docs # for flexibility in building GitHub pages

website:
  title: "Title"
  navbar:
    background: "#000000"
    foreground: "#f1f1f1"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: journal
      dark: vapor
    backgroundcolor: "#f1f1f1"
    linkcolor: "#CC0000"
    linestretch: 1.33
    css: styles.css
    toc: true
    fig-align: center
    reference-location: margin

editor: visual

